
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mz.dmq: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: slsHDC12Kyy9tayuDjVue7JIt0GG3y6U
            client-secret: DmGykhz6D6HQULM9_I_Imbnl-MO2nNp0nEsirx-e498YnJMfMIY-W1HMPU4RNDFE
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://mzaragoza.us.auth0.com/
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  messages:
    basename: i18n/messages