
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DB_DDLAUTO:validate}

# jdbc:postgresql://dondemequede:d0nd3m3qu3d3@192.168.99.102:5432/dmq